language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip python3-dev build-essential

install:
  - easy_install .

script:
  - python3 ci/main.py
